name = "HolomorphicFun"
uuid = "856dd008-ac59-4279-b7ad-7b5f1a10bcbb"
authors = ["Matthew Priddin and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
